#!/bin/sh
/bin/cp -r /app/share/dunedynasty $XDG_DATA_HOME
if ! [ -f "$XDG_DATA_HOME/dunedynasty/data/DUNE.PAK" ]; then
  echo "ERROR: Dune II data files not found."
  echo "Place your Dune2 1.07eu data files in $XDG_DATA_HOME/dunedynasty/data"
else
  /app/bin/dunedynasty
fi